 [[runners]] 
  name = "Docker Runner"
  url = "https://ec2-3-90-87-4.compute-1.amazonaws.com"
  token = "YOUR_TOKEN"
  executor = "docker"
  clone_url = "https://ec2-3-90-87-4.compute-1.amazonaws.com"
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    network_mode = "development"
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
