services:
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      container_name: GitLab
      restart: always
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://ec2-52-90-68-189.compute-1.amazonaws.com:8080'
          gitlab_rails['gitlab_shell_ssh_port'] = 3122
          nginx['listen_port'] = 8080
          nginx['redirect_http_to_https'] = true
          nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server-cert.pem"
          nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server-key.pem"
          registry_external_url 'https://ec2-52-90-68-189.compute-1.amazonaws.com:8080'
          registry_nginx['enable'] = true
          registry_nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server-cert.pem"
          registry_nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server-key.pem"
          gitlab_rails['backup_keep_time'] = 172800
      ports:
        - '8080:8080'
        - '3122:22'
      volumes:
        - '/srv/gitlab/config:/etc/gitlab'
        - '/srv/gitlab/logs:/var/log/gitlab'
        - '/srv/gitlab/ssl:/etc/ssl/certs/gitlab'
        - '/srv/gitlab/data:/var/opt/gitlab'
      networks:
        dev-net:
          aliases:
            - ec2-3-90-87-4.compute-1.amazonaws.com
    runner:
      image: 'gitlab/gitlab-runner:latest'
      container_name: gitlab-runner
      restart: always
      volumes:
        - '/srv/gitlab-runner:/etc/gitlab-runner'
        - '/var/run/docker.sock:/var/run/docker.sock'
      networks:
        - dev-net

networks:
  dev-net:
      name: development
